# Generated by Django 2.2.7 on 2019-11-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='recordComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'Initial'), ('OP', 'Opened'), ('BL', 'Blocked'), ('CL', 'Closed')], default='IN', max_length=2)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.recordComment')),
            ],
        ),
    ]
