# Generated by Django 2.2.7 on 2019-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
